# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_gameinstance_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='platform',
            field=models.CharField(default='', max_length=200),
        ),
    ]
